# Generated by Django 5.2 on 2026-04-25 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercadopago_id', models.CharField(blank=True, max_length=200, verbose_name='ID MP')),
                ('preference_id', models.CharField(blank=True, max_length=200, verbose_name='Preference ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('authorized', 'Autorizado'), ('in_process', 'Em Processamento'), ('in_mediation', 'Em Mediação'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('charged_back', 'Estornado')], default='pending', max_length=20, verbose_name='Status')),
                ('status_detail', models.CharField(blank=True, max_length=200, verbose_name='Detalhe do Status')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método')),
                ('payment_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('payer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email do Pagador')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Resposta Bruta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
