# Generated by Django 5.2 on 2026-04-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('contato', models.CharField(blank=True, max_length=200, verbose_name='Contato')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('prazo_medio_dias', models.PositiveIntegerField(default=15, verbose_name='Prazo Médio (dias)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cartório',
                'verbose_name_plural': 'Cartórios',
                'ordering': ['estado', 'cidade', 'nome'],
                'indexes': [models.Index(fields=['estado', 'cidade'], name='registry_re_estado_5e87b7_idx')],
            },
        ),
    ]
