# Generated by Django 5.2 on 2026-05-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_registry_new_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='registry',
            new_name='registry_re_tipo_se_de0d0c_idx',
            old_name='registry_tipo_servico_idx',
        ),
        migrations.RenameIndex(
            model_name='registry',
            new_name='registry_re_estado_f0a897_idx',
            old_name='registry_estado_cidade_tipo_idx',
        ),
    ]
