# Generated by Django 5.2 on 2026-05-11 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_registry_tipos_servico_json'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='registry',
            new_name='registry_re_ativo_4fed4a_idx',
            old_name='registry_re_ativo_idx',
        ),
    ]
