# Generated by Django 5.2 on 2026-04-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador'), ('financeiro', 'Financeiro'), ('cliente', 'Cliente')], default='cliente', max_length=15, verbose_name='Tipo'),
        ),
    ]
