# Generated by Django 5.2 on 2026-06-14 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_senha_auto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(choices=[('visualizar_usuarios', 'Visualizar Usuários'), ('criar_usuarios', 'Criar Usuários'), ('editar_usuarios', 'Editar Usuários'), ('excluir_usuarios', 'Excluir Usuários'), ('visualizar_clientes', 'Visualizar Clientes'), ('criar_clientes', 'Criar Clientes'), ('editar_clientes', 'Editar Clientes'), ('excluir_clientes', 'Excluir Clientes'), ('visualizar_financeiro', 'Visualizar Financeiro'), ('editar_financeiro', 'Editar Financeiro'), ('visualizar_relatorios', 'Visualizar Relatórios'), ('visualizar_historico', 'Visualizar Histórico'), ('acessar_painel_admin', 'Acessar Painel Administrativo')], max_length=60, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('modulo', models.CharField(choices=[('usuarios', 'Usuários'), ('clientes', 'Clientes'), ('financeiro', 'Financeiro'), ('relatorios', 'Relatórios'), ('historico', 'Histórico'), ('admin', 'Administração')], max_length=20, verbose_name='Módulo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Permissão',
                'verbose_name_plural': 'Permissões',
                'ordering': ['modulo', 'codename'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('permissoes', models.ManyToManyField(blank=True, related_name='roles', to='accounts.permissao', verbose_name='Permissões')),
            ],
            options={
                'verbose_name': 'Papel (Role)',
                'verbose_name_plural': 'Papéis (Roles)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('permissoes_extras', models.ManyToManyField(blank=True, related_name='usuarios_diretos', to='accounts.permissao', verbose_name='Permissões Extras')),
                ('permissoes_negadas', models.ManyToManyField(blank=True, related_name='usuarios_negados', to='accounts.permissao', verbose_name='Permissões Negadas')),
                ('roles', models.ManyToManyField(blank=True, related_name='usuarios', to='accounts.role', verbose_name='Papéis')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_customizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissões do Usuário',
                'verbose_name_plural': 'Permissões dos Usuários',
            },
        ),
    ]
