# Generated by Django 5.2 on 2026-04-25 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoria do Blog',
                'verbose_name_plural': 'Categorias do Blog',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Imagem de Capa')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Resumo')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Título')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
