# Generated by Django 5.2 on 2026-04-30 20:14

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_orderstatuslog_order_cartorio_order_cidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=documents.models.document_upload_path, verbose_name='Arquivo')),
                ('tipo', models.CharField(choices=[('requerimento', 'Requerimento'), ('rg', 'RG / CNH'), ('cpf', 'CPF'), ('comprovante_residencia', 'Comprovante de Residência'), ('certidao_original', 'Certidão Original'), ('procuracao', 'Procuração'), ('comprovante_pagamento', 'Comprovante de Pagamento'), ('documento_entregue', 'Documento Entregue'), ('outros', 'Outros')], default='outros', max_length=30, verbose_name='Tipo')),
                ('nome_original', models.CharField(blank=True, max_length=255, verbose_name='Nome do Arquivo')),
                ('tamanho_bytes', models.PositiveIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('versao', models.PositiveSmallIntegerField(default=1, verbose_name='Versão')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.order')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-data_upload'],
            },
        ),
    ]
