# Generated by Django 5.2 on 2026-05-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_statepricenhistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='statepricehistory',
            new_name='financeiro__service_ce6ec7_idx',
            old_name='fin_sph_service_state_idx',
        ),
        migrations.RenameIndex(
            model_name='statepricehistory',
            new_name='financeiro__created_0a7261_idx',
            old_name='fin_sph_created_idx',
        ),
    ]
