# Generated by Django 5.2 on 2026-07-14 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_rename_fin_sph_service_state_idx_financeiro__service_ce6ec7_idx_and_more'),
        ('orders', '0019_fix_apostilamento_orders'),
        ('products', '0031_rename_ltda_meta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código hierárquico. Ex: 1.1.01', max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], db_index=True, max_length=10, verbose_name='Tipo')),
                ('natureza', models.CharField(choices=[('sintetica', 'Sintética (agrupadora)'), ('analitica', 'Analítica (recebe lançamentos)')], default='analitica', help_text='Sintéticas apenas agrupam; analíticas recebem lançamentos.', max_length=10, verbose_name='Natureza')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('is_system', models.BooleanField(default=False, help_text='Contas criadas pelo sistema não podem ser excluídas.', verbose_name='Conta do Sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filhas', to='financeiro.contacontabil', verbose_name='Conta Pai')),
            ],
            options={
                'verbose_name': 'Conta Contábil',
                'verbose_name_plural': 'Plano de Contas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], db_index=True, max_length=10, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('data_competencia', models.DateField(db_index=True, verbose_name='Data de Competência')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], db_index=True, default='confirmado', max_length=12, verbose_name='Status')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('', '—'), ('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('boleto', 'Boleto'), ('transferencia', 'Transferência'), ('dinheiro', 'Dinheiro'), ('outro', 'Outro')], max_length=20, verbose_name='Forma de Pagamento')),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('venda', 'Venda (automático)')], db_index=True, default='manual', max_length=10, verbose_name='Origem')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conta', models.ForeignKey(limit_choices_to={'natureza': 'analitica'}, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.contacontabil', verbose_name='Conta')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
                'ordering': ['-data_competencia', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicoContaReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conta', models.ForeignKey(limit_choices_to={'natureza': 'analitica', 'tipo': 'receita'}, on_delete=django.db.models.deletion.PROTECT, related_name='servicos_vinculados', to='financeiro.contacontabil', verbose_name='Conta de Receita')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_receita_vinculo', to='products.product', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Vínculo Serviço → Conta',
                'verbose_name_plural': 'Vínculos Serviço → Conta',
                'ordering': ['conta__codigo', 'service__name'],
            },
        ),
        migrations.AddIndex(
            model_name='contacontabil',
            index=models.Index(fields=['tipo', 'is_active'], name='financeiro__tipo_0458e0_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['tipo', 'status', '-data_competencia'], name='financeiro__tipo_e94016_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['conta', '-data_competencia'], name='financeiro__conta_i_f0c5a4_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['origem', 'order'], name='financeiro__origem_275290_idx'),
        ),
    ]
