# Generated by Django 5.2 on 2026-04-30 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=30, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(max_length=30, verbose_name='Novo Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Histórico de Status',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='cartorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='registry.registry', verbose_name='Cartório'),
        ),
        migrations.AddField(
            model_name='order',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='order',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AddField(
            model_name='order',
            name='data_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio'),
        ),
        migrations.AddField(
            model_name='order',
            name='estado',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado (UF)'),
        ),
        migrations.AddField(
            model_name='order',
            name='prazo_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo de Entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='order',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='order',
            name='sla_horas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='SLA (horas)'),
        ),
        migrations.AddField(
            model_name='order',
            name='tipo_certidao',
            field=models.CharField(blank=True, choices=[('nascimento', 'Certidão de Nascimento'), ('casamento', 'Certidão de Casamento'), ('obito', 'Certidão de Óbito'), ('imovel', 'Certidão de Imóvel'), ('interdicao', 'Certidão de Interdição'), ('procuracao', 'Certidão de Procuração'), ('cnd_federal', 'CND Federal'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Certidão'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Aguardando Pagamento'), ('paid', 'Pago'), ('novo', 'Novo'), ('em_analise', 'Em Análise'), ('aguardando_documentos', 'Aguardando Documentos'), ('em_processamento', 'Em Processamento'), ('em_cartorio', 'Em Cartório'), ('pronto_envio', 'Pronto para Envio'), ('enviado', 'Enviado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('refunded', 'Reembolsado'), ('processing', 'Processando'), ('completed', 'Completo')], default='pending', max_length=30, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['responsavel', 'status'], name='orders_orde_respons_8b34d9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['prazo_entrega'], name='orders_orde_prazo_e_47bc55_idx'),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
