# Generated by Django 5.2 on 2026-05-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cartitem_state_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tipo_certidao',
            field=models.CharField(blank=True, choices=[('nascimento', 'Certidão de Nascimento'), ('casamento', 'Certidão de Casamento'), ('obito', 'Certidão de Óbito'), ('imovel', 'Certidão de Imóvel'), ('interdicao', 'Certidão de Interdição'), ('procuracao', 'Certidão de Procuração'), ('escritura', 'Certidão de Escritura'), ('cnd_federal', 'CND Federal'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Certidão'),
        ),
    ]
