# Generated by Django 5.2 on 2026-05-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_tipo_certidao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tipo_certidao',
            field=models.CharField(blank=True, choices=[('nascimento', 'Certidão de Nascimento'), ('casamento', 'Certidão de Casamento'), ('obito', 'Certidão de Óbito'), ('imovel', 'Certidão de Imóvel'), ('interdicao', 'Certidão de Interdição'), ('procuracao', 'Certidão de Procuração'), ('escritura', 'Certidão de Escritura'), ('uniao_estavel', 'Certidão de Escritura de União Estável'), ('escritura_ata_notarial', 'Certidão de Escritura de Ata Notarial'), ('escritura_compra_venda', 'Certidão de Escritura de Compra e Venda'), ('escritura_divorcio', 'Certidão de Escritura de Divórcio'), ('escritura_doacao', 'Certidão de Escritura de Doação'), ('escritura_emancipacao', 'Certidão de Escritura de Emancipação'), ('escritura_hipoteca', 'Certidão de Escritura de Hipoteca'), ('escritura_inventario', 'Certidão de Escritura de Inventário'), ('escritura_pacto_antenupcial', 'Certidão de Escritura de Pacto Antenupcial'), ('escritura_permuta', 'Certidão de Escritura de Permuta'), ('escritura_testamento', 'Certidão de Escritura de Testamento'), ('cnd_federal', 'CND Federal'), ('outros', 'Outros')], max_length=40, verbose_name='Tipo de Certidão'),
        ),
    ]
