# Generated by Django 5.2 on 2026-05-11 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_categoria_painel'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_categor_f3835c_idx',
            old_name='orders_order_cat_created_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_categor_2576c7_idx',
            old_name='orders_order_cat_status_idx',
        ),
    ]
