# Generated by Django 5.2 on 2026-05-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_tipo_certidao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='tipo_certidao',
            field=models.CharField(blank=True, max_length=40, verbose_name='Tipo de Certidão'),
        ),
    ]
