# Generated by Django 5.2 on 2026-05-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_tipo_certidao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tipo_certidao',
            field=models.CharField(blank=True, choices=[('nascimento', 'Certidão de Nascimento'), ('casamento', 'Certidão de Casamento'), ('obito', 'Certidão de Óbito'), ('imovel', 'Certidão de Imóvel'), ('imovel_matricula_atualizada', 'Certidão de Matrícula Atualizada'), ('imovel_alienacao_fiduciaria', 'Certidão Negativa de Alienação Fiduciária'), ('imovel_onus_reais', 'Certidão de Ônus Reais'), ('imovel_pesquisa_bens', 'Pesquisa de Bens'), ('imovel_penhor_safra', 'Certidão de Penhor de Safra'), ('imovel_pacote_compra_venda', 'Pacote Compra e Venda de Imóvel'), ('interdicao', 'Certidão de Interdição'), ('procuracao', 'Certidão de Procuração'), ('escritura', 'Certidão de Escritura'), ('uniao_estavel', 'Certidão de Escritura de União Estável'), ('escritura_ata_notarial', 'Certidão de Escritura de Ata Notarial'), ('escritura_compra_venda', 'Certidão de Escritura de Compra e Venda'), ('escritura_divorcio', 'Certidão de Escritura de Divórcio'), ('escritura_doacao', 'Certidão de Escritura de Doação'), ('escritura_emancipacao', 'Certidão de Escritura de Emancipação'), ('escritura_hipoteca', 'Certidão de Escritura de Hipoteca'), ('escritura_inventario', 'Certidão de Escritura de Inventário'), ('escritura_pacto_antenupcial', 'Certidão de Escritura de Pacto Antenupcial'), ('escritura_permuta', 'Certidão de Escritura de Permuta'), ('escritura_testamento', 'Certidão de Escritura de Testamento'), ('cnd_federal', 'CND Federal'), ('fgts_inss', 'FGTS / INSS'), ('cnd_estadual', 'CND Estadual'), ('cnd_itr', 'CND ITR'), ('cnj_improbidade', 'CNJ Improbidade Administrativa'), ('cafir', 'CAFIR'), ('ibama_embargos', 'IBAMA Embargos'), ('certidao_negativa_acoes_criminais', 'Certidão Negativa de Ações Criminais'), ('certidao_negativa_debitos_ambientais', 'Certidão Negativa de Débitos Ambientais'), ('certidao_negativa_municipio', 'Certidão Negativa Municipal'), ('cota_legal_pcds', 'Cota Legal de PCDs'), ('debitos_trabalhistas', 'Débitos Trabalhistas'), ('propriedade_aeronave', 'Certidão de Propriedade de Aeronave'), ('junta_comercial', 'Junta Comercial'), ('regularidade_crea', 'Regularidade CREA'), ('antecedentes_criminais', 'Antecedentes Criminais'), ('tse_quitacao_eleitoral', 'TSE Quitação Eleitoral'), ('fed_estadual_outros', 'Outros Federais/Estaduais'), ('apostila_haia', 'Apostila de Haia'), ('traducao_juramentada', 'Tradução Juramentada'), ('busca_protesto', 'Busca de Protesto'), ('busca_testamento', 'Certidão Negativa de Testamento'), ('outros', 'Outros')], max_length=40, verbose_name='Tipo de Certidão'),
        ),
    ]
