# Generated by Django 5.2 on 2026-04-30 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_orderstatuslog_order_cartorio_order_cidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('novo_pedido', 'Novo Pedido'), ('status_alterado', 'Status Alterado'), ('atraso', 'Pedido Atrasado'), ('prazo_proximo', 'Prazo Próximo'), ('enviado', 'Pedido Enviado'), ('concluido', 'Pedido Concluído'), ('documento_recebido', 'Documento Recebido'), ('pagamento_aprovado', 'Pagamento Aprovado')], max_length=30, verbose_name='Tipo')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['usuario', 'lida', '-data'], name='notificatio_usuario_5fa4ec_idx')],
            },
        ),
    ]
