# Generated by Django 5.2 on 2026-05-02 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_state_servicestateprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicestateprice',
            options={'ordering': ['state__name'], 'verbose_name': 'Preço por Estado', 'verbose_name_plural': 'Preços por Estado'},
        ),
        migrations.RenameIndex(
            model_name='servicestateprice',
            new_name='products_se_service_bab085_idx',
            old_name='products_se_service_idx',
        ),
    ]
