# Generated by Django 5.2 on 2026-05-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_seed_preco_imovel_matricula'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='precoimovelestado',
            name='unique_tipo_certidao_state',
        ),
        migrations.RenameIndex(
            model_name='precoimovelestado',
            new_name='products_pr_tipo_ce_314a95_idx',
            old_name='products_pr_tipo_ce_idx',
        ),
        migrations.AlterUniqueTogether(
            name='precoimovelestado',
            unique_together={('tipo_certidao', 'state')},
        ),
    ]
