# Generated by Django 5.2 on 2026-05-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_is_system_service_has_fixed_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_fixed_price',
            field=models.BooleanField(default=False, help_text='Quando ativo, o preço é fixo (R$ 49,90 para Federais e Estaduais) independente do estado. Não usa tabela ServiceStatePrice.', verbose_name='Preço Fixo Global'),
        ),
    ]
