# Generated by Django 5.2.3 on 2026-05-19 19:16

from django.db import migrations


def deactivate_certidao_negativa_testamento(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Product.objects.filter(slug='certidao-negativa-de-testamento').update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0024_hide_nav_categories"),
    ]

    operations = [
        migrations.RunPython(
            deactivate_certidao_negativa_testamento,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
